# Generated by Django 2.1.5 on 2019-01-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistoricData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockSymbol', models.CharField(max_length=50)),
                ('open', models.DecimalField(decimal_places=6, max_digits=12)),
                ('close', models.DecimalField(decimal_places=6, max_digits=12)),
                ('low', models.DecimalField(decimal_places=6, max_digits=12)),
                ('high', models.DecimalField(decimal_places=6, max_digits=12)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
