# Generated by Django 2.1.5 on 2019-01-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stockhistoricdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistoricdata',
            name='volume',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
