# Generated by Django 2.1.5 on 2019-01-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190111_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistoricdata',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockhistoricdata',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockhistoricdata',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockhistoricdata',
            name='open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockhistoricdata',
            name='volume',
            field=models.FloatField(),
        ),
    ]
